const COLORS = {
  PRIMARY: '#7A27E4',
  SECONDARY: '#2D2833',
  BACKGROUND: '#f5f5f5',
  TEXT: '#FFFF',
  ERROR: '#e74c3c',
  LISTBACKGROUND: '#16111C',
  WHITE: '#FFFF',
  DARK: '#333',
  BUTTONCOLOR: '#FFAB17',
  DESCRIPTIONTEXT: '#DDD',
};

export default COLORS;
